### ISSUE TITLE
Crash during startup due to already existing tables

### ISSUE THREAD

**Issue by Jakob37** [Clinical-Genomics/chanjo2#246]
When using persistant volume for mariadb, Chanjo2 crashes during startup if the tables already have been created.

```
api_chanjotest  | [2024-03-07 09:31:41 +0000] [8] [ERROR] Traceback (most recent call last):
api_chanjotest  |   File "/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1969, in _exec_single_context
api_chanjotest  |     self.dialect.do_execute(
api_chanjotest  |   File "/venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
api_chanjotest  |     cursor.execute(statement, parameters)
api_chanjotest  |   File "/venv/lib/python3.11/site-packages/MySQLdb/cursors.py", line 179, in execute
api_chanjotest  |     res = self._query(mogrified_query)
api_chanjotest  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api_chanjotest  |   File "/venv/lib/python3.11/site-packages/MySQLdb/cursors.py", line 330, in _query
api_chanjotest  |     db.query(q)
api_chanjotest  |   File "/venv/lib/python3.11/site-packages/MySQLdb/connections.py", line 255, in query
api_chanjotest  |     _mysql.connection.query(self, query)
api_chanjotest  | MySQLdb.OperationalError: (1050, "Table 'genes' already exists")
```

Relevant parts of my docker compose file:

```
chanjo2:                                                                                           
  build:                                                                                           
    context: /home/user/src/chanjo2                                                               
  container_name: api_chanjotest                                                                                                                      
  ports:                                                                                           
    - '8817:8000'                                                                                  
  depends_on:                                                                                      
    mariadb:                                                                                       
      condition: service_healthy                                                                   
  volumes:                                                                                         
    - /home/user/src/chanjo2:/home/worker/app                                                     
    - /home/user/src/scout/scout:/home/worker/app/scout                                           
    - /home/user/src/chanjo2/template.env:/home/worker/app/.env                                   
    - /home/user/data/scout:/data                                                                                                             
  networks:                                                                                        
    - scout-net                                                                                    
mariadb:                                                                                           
  container_name: mariadb                                                                          
  build:                                                                                           
    context: /home/user/src/chanjo2                                                               
    dockerfile: Dockerfile-db                                                                      
  restart: 'always'                                                                                
  environment:                                                                                     
    - MYSQL_USER=${MYSQL_USER}                                                                     
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}                                                             
    - MYSQL_DATABASE=${MYSQL_DATABASE_NAME}                                                        
    - MARIADB_RANDOM_ROOT_PASSWORD=T                                                               
  healthcheck:                                                                                                                  
    test: "mariadb --user=${MYSQL_USER} --password=${MYSQL_PASSWORD} --execute \"SHOW DATABASES;\""
    timeout: 5s                                                                                    
    retries: 6                                                                                     
  volumes:                                                                                         
    - mysql:/home/worker/DBs                                                                       
  networks:                                                                                        
    - scout-net                                                                                    
  ports:                                                                                           
    - 3307:3306                                                                                    
  expose:                                                                                          
    - 3306                                                                                         
volumes:          
  mysql:          
    driver: local 
```

If I remove the `mysql` volume, then it will recreate it and it will start correctly once. (If I then take it down and up again, it will crash due to already created tables again)
